services:
  - type: web
    name: visionx-codeavengers-od-08
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .."
    startCommand: "uvicorn backend.app:app --host 0.0.0.0 --port $PORT --workers 1 --limit-max-requests 200"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: NODE_VERSION
        value: 18.17.0
